@startuml AddTripSequenceDiagram
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddTripCommandParser" as AddTripParser LOGIC_COLOR
participant "a:AddTripCommand" as AddCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute()
activate LogicManager

LogicManager -> AddressBookParser : parseCommand()
activate AddressBookParser

AddressBookParser -> AddTripParser : parse()
activate AddTripParser

AddTripParser -> AddTripParser : parseTripName()
AddTripParser -> AddTripParser : parseAccommodation()
AddTripParser -> AddTripParser : parseItinerary()
AddTripParser -> AddTripParser : parseTripDate()
AddTripParser -> AddTripParser : parseName()
AddTripParser -> AddTripParser : parseNote()

create AddCommand
AddTripParser -> AddCommand
activate AddCommand

AddCommand --> AddTripParser
deactivate AddCommand

AddTripParser --> AddressBookParser : a
deactivate AddTripParser

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> AddCommand : execute()
activate AddCommand

AddCommand -> Model : hasTrip()
activate Model
Model --> AddCommand
deactivate Model

AddCommand -> Model : addTrip()
activate Model
Model --> AddCommand
deactivate Model

AddCommand --> LogicManager : result
deactivate AddCommand
AddCommand -[hidden]-> LogicManager : result

[<-- LogicManager
deactivate LogicManager
@enduml 