@startuml DeleteContactSequenceDiagram
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "d:DeleteContactCommand" as DeleteCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":AddressBook" as AddressBook MODEL_COLOR
end box

[-> LogicManager : execute("deleteContact 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("deleteContact 1")
activate AddressBookParser

create DeleteCommand
AddressBookParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> AddressBookParser
deactivate DeleteCommand

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeleteCommand : execute()
activate DeleteCommand

DeleteCommand -> Model : getFilteredPersonList()
activate Model
Model --> DeleteCommand : filteredList
deactivate Model

DeleteCommand -> DeleteCommand : validateIndex(1)

DeleteCommand -> Model : deletePerson(contact)
activate Model
Model -> AddressBook : removePerson(contact)
activate AddressBook
AddressBook --> Model
deactivate AddressBook
Model --> DeleteCommand
deactivate Model

DeleteCommand --> LogicManager : result
deactivate DeleteCommand
DeleteCommand -[hidden]-> LogicManager : result
destroy DeleteCommand

[<-- LogicManager
deactivate LogicManager
@enduml